module.exports = {
	skipWords: [
		// The checker strips digits before matching, so 'abc' also covers tokens like 'abc123'
		'abc',
		'abc123',
		'alice',
		'backoff',
		'fatlard1993',
		'gameplay',
		'lowdb',
		'microtask',
		'multiplayer',
		'namespacing',
		'os',
		'reconnection',
		'reconnections',
		'rss',
		'stringified',
		'svg',
		'tmpdir',
		'uptime',
		'websocket',
		'websockets',
		'wildcard',
		'wildcards',
	],
};
